services:
  db:
    image: postgres:16-alpine
    container_name: ajaia-docs-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ajaia
      POSTGRES_PASSWORD: ajaia
      POSTGRES_DB: ajaia_docs
    volumes:
      - ajaia_docs_data:/var/lib/postgresql/data

volumes:
  ajaia_docs_data:
